# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0208e82449e37e7176f628eb9d3058324cc13f86cee1793c706e29941c78817ce25c6d80893da3e6b77be782e0a5ce5684830d3ed9915f3f040f2404d7567e

test:
  secret_key_base: 34adff042780ed02526d2f92eebf62ba957f1745f95cf26bea75abcc0adb440b137f4270c07b7e363ec21314749870a85fcf9c4a5e3732292f757b44112ee553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
